swagger: '2.0'
info:
  title: Authentication-provider REST API
  version: 1.0.0
  description: 'Manage, order, enable and disable GeoServer authentication providers.


    Each provider is marshalled inside an element / property whose **key

    is its concrete class name**.

    '
paths:
  /security/authProviders:
    get:
      summary: List providers (active order)
      tags:
      - authProviders
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/authProviders'
          examples:
            application/json:
              authProviders:
                org.geoserver.security.config.UsernamePasswordAuthenticationProviderConfig:
                  id: 52857278:13c7ffd66a8:-7ff0
                  name: default
                  className: org.geoserver.security.auth.UsernamePasswordAuthenticationProvider
                  userGroupServiceName: default
        '403':
          description: Forbidden
        '500':
          description: Server error
      produces:
      - application/json
      - application/xml
    post:
      summary: Create a provider
      tags:
      - authProviders
      consumes:
      - application/json
      - application/xml
      parameters:
      - in: query
        name: position
        description: Optional insert position (0-based). Omit to append.
        type: integer
        minimum: 0
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/authProvider'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/authProvider'
          headers:
            Location:
              type: string
              format: uri
        '400':
          description: Validation error
        '403':
          description: Forbidden
        '500':
          description: Server error
      produces:
      - application/json
      - application/xml
  /security/authProviders/{providerName}:
    get:
      summary: Get provider
      tags:
      - authProviders
      parameters:
      - &id001
        name: providerName
        in: path
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/authProviderCore'
          examples:
            application/json:
              org.geoserver.security.config.UsernamePasswordAuthenticationProviderConfig:
                id: 52857278:13c7ffd66a8:-7ff0
                name: default
                className: org.geoserver.security.auth.UsernamePasswordAuthenticationProvider
                userGroupServiceName: default
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Server error
      produces:
      - application/json
      - application/xml
    put:
      summary: Update provider
      tags:
      - authProviders
      consumes:
      - application/json
      - application/xml
      parameters:
      - *id001
      - in: query
        name: position
        description: Move provider to this position
        type: integer
        minimum: 0
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/authProvider'
      responses:
        '200':
          description: Updated
          schema:
            $ref: '#/definitions/authProviderCore'
        '400':
          description: Validation error
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Server error
      produces:
      - application/json
      - application/xml
    delete:
      summary: Delete provider
      tags:
      - authProviders
      parameters:
      - *id001
      responses:
        '200':
          description: Deleted
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Server error
      produces:
      - application/xml
    parameters:
    - *id001
  /security/authProviders/order:
    put:
      summary: Replace active order (enables / disables providers)
      tags:
      - authProviders
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/authProviderOrder'
      responses:
        '200':
          description: Order updated
        '400':
          description: Validation error
        '403':
          description: Forbidden
        '500':
          description: Server error
      produces:
      - application/xml
    get:
      summary: Method not allowed
      responses:
        '405':
          description: Use PUT
      produces:
      - application/xml
    post:
      summary: Method not allowed
      responses:
        '405':
          description: Use PUT
      produces:
      - application/xml
      consumes:
      - application/xml
    delete:
      summary: Method not allowed
      responses:
        '405':
          description: Use PUT
      produces:
      - application/xml
      consumes:
      - application/xml
host: localhost:8080
basePath: /geoserver/rest
schemes:
- http
security:
- basicAuth: []
definitions:
  authProviderCore:
    type: object
    required:
    - className
    - id
    - name
    - userGroupServiceName
    additionalProperties: true
    properties:
      id:
        type: string
        description: Server-generated identifier (omit on POST)
      name:
        type: string
      className:
        type: string
      userGroupServiceName:
        type: string
    xml:
      name: org.geoserver.security.config.UsernamePasswordAuthenticationProviderConfig
  authProvider:
    $ref: '#/definitions/authProviderCore'
  authProviders:
    type: array
    xml:
      name: authProviders
      wrapped: true
    items:
      $ref: '#/definitions/authProviderCore'
  authProviderOrder:
    type: object
    required:
    - order
    properties:
      order:
        type: array
        items:
          type: string
          xml:
            name: order
        xml:
          name: order
          wrapped: false
    example:
      order:
      - default
      - corporateLdap
    xml:
      name: authProviderOrder
securityDefinitions:
  basicAuth:
    type: basic
    description: GeoServer administrator credentials
