
swagger: '2.0'
info:
  version: 1.0.0
  title: Provider Rest endpoints
  description: Management of Provider Configuration data
  contact:
    name: GeoServer
    email: 'geoserver-users@osgeo.org'
    url: 'https://geoserver.org/comm/'
securityDefinitions:
  basicAuth: # <-- arbitrary name for the security scheme
    type: basic
    description: The user name and password of a admin user.

schemes:
  - https
  - http
host: localhost
basePath: /geoserver/rest/security

paths:
  /authProviders:
    get:
      security:
        - basicAuth: []
      operationId: listAuthProviders
      tags:
        - "AuthProviders"
      summary: List all the auth providers available in the system.
      description: List all the auth providers available in the system.
      produces:
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/AuthProviders"
          examples:
            application/xml: |
              <authProviderList>
                <authProvider>
                  <id>-4e7ef1a4:196d967dcea:-8000</id>
                  <name>-4e7ef1a4:196d967dcea:-8000</name>
                  <className>org.geoserver.security.jdbc.config.JDBCConnectAuthProviderConfig</className>
                  <userGroupServiceName>default</userGroupServiceName>
                  <position>-1</position>
                  <config class="org.geoserver.security.jdbc.config.JDBCConnectAuthProviderConfig">
                    <id>-4e7ef1a4:196d967dcea:-8000</id>
                    <name>JDBC</name>
                    <className>org.geoserver.security.jdbc.JDBCConnectAuthProvider</className>
                    <driverClassName>org.postgresql.Driver</driverClassName>
                    <connectURL>Jdbc::/postgresSQl</connectURL>
                    <userGroupServiceName>default</userGroupServiceName>
                  </config>
                  <disabled>true</disabled>
                </authProvider>
            application/json: |
              {
                "authProviderList": {
                  "authProvider": [
                    {
                      "id": "-4e7ef1a4:196d967dcea:-8000",
                      "name": "-4e7ef1a4:196d967dcea:-8000",
                      "className": "org.geoserver.security.jdbc.config.JDBCConnectAuthProviderConfig",
                      "userGroupServiceName": "default",
                      "position": -1,
                      "config": {
                        "@class": "org.geoserver.security.jdbc.config.JDBCConnectAuthProviderConfig",
                        "id": "-4e7ef1a4:196d967dcea:-8000",
                        "name": "JDBC",
                        "className": "org.geoserver.security.jdbc.JDBCConnectAuthProvider",
                        "driverClassName": "org.postgresql.Driver",
                        "connectURL": "Jdbc::/postgresSQl",
                        "userGroupServiceName": "default"
                      },
                      "disabled": true
                    },
                  ]
                }
              }
        500:
          description: INTERNAL_SERVER_ERROR
    post:
      security:
        - basicAuth: []
      operationId: createAuthProvider
      description: |
        This method will create the specified authentication provider on the server. 
        The name of the provider must be unique. It expects the id field to be
        omitted as the server will generate this value.
      tags:
        - "AuthProviders"
      summary: Create a new auth provider
      consumes:
        - application/xml
        - application/json
      produces:
        - application/xml
        - application/json
      responses:
        201:
          description: |
            The provider configuration has been saved on the server
          schema:
            $ref: "#/definitions/AuthProvider"
          
          examples:
            application/xml: |
        400:
          description: |
            The data supplied by the client was invalid. Typically check that the name 
            is unqiue and that no id is supplied.
  /authProviders/{providerName}:
    get:
      security:
        - basicAuth: []
      operationId: viewAuthProvider
      tags:
        - "AuthProviders"
      summary: Views the details of a single provider.
      description: |
        Displays the contents of the configuration object on the server.
      produces:
        - application/xml
        - application/json
      responses:
        200:
          description: |
            The request completed successfully and the name provider configuration 
            has been returned.
          examples:
            application/xml: |
              <authProvider>
                  <id>7787843a:196d38d0a14:-7fcc</id>
                  <name>7787843a:196d38d0a14:-7fcc</name>
                  <className>org.geoserver.security.config.UsernamePasswordAuthenticationProviderConfig</className>
                  <userGroupServiceName>default</userGroupServiceName>
                  <position>0</position>
                  <config class="org.geoserver.security.config.UsernamePasswordAuthenticationProviderConfig">
                      <id>7787843a:196d38d0a14:-7fcc</id>
                      <name>default</name>
                      <className>org.geoserver.security.auth.UsernamePasswordAuthenticationProvider</className>
                      <userGroupServiceName>default</userGroupServiceName>
                  </config>
                  <disabled>false</disabled>
              </authProvider>
            application/json: |
              {
                "authProvider": {
                  "id": "7787843a:196d38d0a14:-7fcc",
                  "name": "7787843a:196d38d0a14:-7fcc",
                  "className": "org.geoserver.security.config.UsernamePasswordAuthenticationProviderConfig",
                  "userGroupServiceName": "default",
                  "position": 0,
                  "config": {
                    "@class": "org.geoserver.security.config.UsernamePasswordAuthenticationProviderConfig",
                    "id": "7787843a:196d38d0a14:-7fcc",
                    "name": "default",
                    "className": "org.geoserver.security.auth.UsernamePasswordAuthenticationProvider",
                    "userGroupServiceName": "default"
                  },
                  "disabled": false
                }
              }
          schema:
            $ref: "#/definitions/AuthProvider"
        404:
          description: |
            The named configuration does not exist on the server
        500:
          description: |
            A problem occurred within the server, this cannot be fixed by changing the data
            in the request contact you administrator
    put:
      security:
        - basicAuth: []
      operationId: updateAuthProvider
      tags:
        - "AuthProviders"
      summary: Update the named provider configuration.
      description: |
        Update the named provider configuration.
      consumes:
        - application/xml
        - application/json
      produces:
        - application/xml
        - application/json
      responses:
        200:
          description: |
            The configuration has been updated
          schema:
            $ref: "#/definitions/AuthProviders"
        400:
          description: |
            The provider configuration cannot be updated. Check that the supplied name matches
            the name in the body of the request. Check that the Id matches the Id of the 
            configuration in memory. Check all required fields the type of authentication
            provider have been supplied.
        500:
          description: |
            The server is experiencing some issue. If this persists contact your administrator.
    delete:
      security:
        - basicAuth: []
      operationId: deleteAuthProvider
      tags:
        - "AuthProviders"
      summary: Deletes the named provider.
      description: |
        Removes the authentication configuration from the server.
      responses:
        200:
          description: |
            The authentication provider was successfully removed
        410:
          description: |
            The authentication provider does not exist or has already been removed
        500:
          description: |
            The server is experiencing some issue. If this persists contact your administrator.
definitions:
  AuthProviders:
    title: Auth Providers
    type: array
    items:
      $ref: "#/definitions/AuthProvider"
  AuthProvider:
    title: Auth Provider
    type: object
    properties:
      id:
        type: string
        description: |
          The unique id assigned to the configuration by geoserver
      name:
        type: string
        description: |
          The unique name assigned to the configuration by client
      position:
        type: string
        description: |
          The index of the provider, -1 if disabled
      disabled:
        type: boolean
        description: |
          True when the provider is disabled
      config:
        type: object
        description: |
          Bespoke configuration fields required by the specific type
          of authentication provider
        properties:
          className:
            type: string
            description: |
              The className of the actual provider class used in geoserver
          AnyValue: {}
        required:
          - className
    required:
      - id
      - name
      - config